name: "Development"

on:
  pull_request:
    branches:
      - develop
    types:
      - opened

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    if: startsWith(github.head_ref, 'feature/')
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev